### ISSUE TITLE
doh-client panics when connecting no_cookies = true

### ISSUE THREAD

**Issue by ookangzheng** [m13253/dns-over-https#16]
I updated to latest git version and reinstall on my Mac High Sierra
my upstream server is 1.0.0.1, and I dig google.com @127.0.0.1 not responding
<img width="1167" alt="screen shot 2018-07-03 at 23 09 05" src="https://user-images.githubusercontent.com/6301735/42228352-576f86d8-7f16-11e8-88e2-8537b3a175f0.png">

**Comment by m13253** [comment]
Would you please give me a longer screenshot?

**Comment by m13253** [comment]
I guessed your configuration but couldn't reproduce the bug.

Here is my guessed configuration, is it close to yours?
```toml
listen = ["127.0.0.1:53", "[::1]:53"]
upstream_google = [
    "https://1.1.1.1/dns-query",
    "https://1.0.0.1/dns-query",
]
upstream_ietf = []
bootstrap = []
timeout = 30
no_ecs = false
no_cookie = false
no_ipv6 = false
verbose = true
```

Please paste your configuration file, with a longer screenshot of Console.app.
