### ISSUE TITLE
怎么会出现错误："no such host"

### ISSUE THREAD

**Issue by luckypoem** [m13253/dns-over-https#65]
hi.
在mac上的doh-client.conf里，我启用了：
[[upstream.upstream_ietf]]
url = "https://doh.dns.sb/dns-query"
weight = 50

然后，我运行：sudo  $GOBIN/doh-client -conf ~/doh-client.conf
显示：
2019/12/06 20:57:15 Get https://doh.dns.sb/dns-query?ct=application/dns-message&dns=AAABAAABAAAAAAABA3d3dwdnc3RhdGljA2NvbQAAAQABAAApEAAAAAAAAAA: dial tcp: lookup doh.dns.sb: no such host
怎么回事，如何解决？

**Comment by m13253** [comment]
你配置 bootstrap 了吗？

**Comment by luckypoem** [comment]
怎么配置 bootstrap ？不会配置，可以在此贴出来吗？

**Comment by m13253** [comment]
看配置文件的这一节内容：
```toml
[others]
# Bootstrap DNS server to resolve the address of the upstream resolver
# If multiple servers are specified, a random one will be chosen each time.
# If empty, use the system DNS settings.
# If you want to preload IP addresses in /etc/hosts instead of using a
# bootstrap server, please make this list empty.
bootstrap = [

    # Google's resolver, bad ECS, good DNSSEC
    "8.8.8.8:53",
    "8.8.4.4:53",

    # CloudFlare's resolver, bad ECS, good DNSSEC
    #"1.1.1.1:53",
    #"1.0.0.1:53",

]
```
把方括号里的内容改成：
```toml
[others]
bootstrap = [
    "223.5.5.5:53",
    "223.6.6.6:53",
]
```
这样的话，就可以使用阿里云 DNS 来解析 doh.dns.sb 域名，解决鸡生蛋问题。
